version: '3.8'

services:
  # backend
  server:
    build: ./server
    container_name: tedd-server
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL} 
      PORT: ${PORT}
      CLIENT_URL: ${CLIENT_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    volumes:
      - ./server:/app
      - /app/node_modules

  # frontend
  client:
    build: ./client
    container_name: tedd-client
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules